version: '3.7'

services: 
  
  db:
    image: mysql
    container_name: angular-ecommerce-db
    hostname: angular-ecommerce-db
    environment:
      MYSQL_ROOT_PASSWORD: AngularEcommerceDev2020!
      MYSQL_DATABASE: angular-ecommerce
    restart: always
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - 3308:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: angular-ecommerce-phpmyadmin
    environment: 
      PMA_HOST: angular-ecommerce-db
      MYSQL_ROOT_PASSWORD: AngularEcommerceDev2020!
    restart: always
    ports: 
      - 8080:80
    depends_on:
      - db